# Generated by Django 2.2.1 on 2019-05-31 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_droidparts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='droidparts',
            name='address',
            field=models.CharField(help_text='Endereço completo', max_length=255),
        ),
        migrations.AlterField(
            model_name='droidparts',
            name='contact_information',
            field=models.CharField(help_text='Informações de contato', max_length=255),
        ),
        migrations.AlterField(
            model_name='droidparts',
            name='description',
            field=models.CharField(help_text='Descrição do produto', max_length=255),
        ),
    ]
