# Generated by Django 2.2.1 on 2019-05-31 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_droidparts_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='droidparts',
            name='user',
        ),
    ]
