# Generated by Django 2.2.1 on 2019-05-31 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190531_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='droidparts',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='droidparts',
            name='user_profile_id',
            field=models.DecimalField(decimal_places=0, default=None, max_digits=8),
        ),
    ]
